#!/usr/bin/env python3
"""
Unified script to:
1. Query ArcGIS Map Server for all traffic segments
2. Extract document IDs from segment attributes
3. Batch download all documents from OnBase
4. Optionally extract metrics from PDFs
"""

import os
import json
import requests
import subprocess
from pathlib import Path
from typing import List, Dict, Any, Optional
import time
import argparse
import sys

# Configuration
MAP_SERVER_URL = "https://gisarc2022.glastonbury-ct.gov/server/rest/services/GlastonburyPublic/StreetsExB/MapServer/1/query"
ONBASE_API_URL = "https://onbasepublic.glastonbury-ct.gov/PublicAccess/api/Document"
OUTPUT_DIR = Path("traffic_data")
TIMEOUT = 30

# Create output directory
OUTPUT_DIR.mkdir(exist_ok=True)


def fetch_all_segments() -> List[Dict]:
    """
    Query the ArcGIS Map Server for all traffic segments.
    Uses the same endpoint as scripty.py
    """
    print("🔍 Querying ArcGIS Map Server for all segments...")
    
    params = {
        "where": "1=1",
        "outFields": "*",
        "returnGeometry": "false",
        "f": "json"
    }
    
    try:
        response = requests.get(MAP_SERVER_URL, params=params, timeout=TIMEOUT)
        response.raise_for_status()
        
        data = response.json()
        
        if "error" in data:
            print(f"⚠ Map server error: {data['error']}")
            return []
        
        features = data.get("features", [])
        print(f"✅ Found {len(features)} segments on the map\n")
        
        return features
        
    except Exception as e:
        print(f"❌ Failed to fetch segments: {e}\n")
        return []


def extract_document_ids_from_segments(segments: List[Dict]) -> Dict[str, Dict]:
    """
    Extract document IDs from segment attributes.
    
    Returns:
        Dict mapping segment ID/name to document info
    """
    print("🔎 Extracting document IDs from segments...")
    
    documents = {}
    
    # Common field names that might contain document IDs
    doc_id_fields = [
        'TrafficPDFURL', 'DocumentID', 'OnBaseID', 'PDFHash',
        'Traffic_PDF', 'Doc_ID', 'traffic_document', 'pdf_url',
        'OBJECTID', 'OID_', 'ID'
    ]
    
    for i, segment in enumerate(segments):
        attributes = segment.get("attributes", {})
        
        # Try to find a document ID
        doc_id = None
        doc_field = None
        
        for field in doc_id_fields:
            if field in attributes and attributes[field]:
                potential_id = str(attributes[field])
                # Check if it looks like an OnBase ID (encoded string)
                if len(potential_id) > 40 and '%' in potential_id:
                    doc_id = potential_id
                    doc_field = field
                    break
        
        if doc_id:
            segment_id = attributes.get('OBJECTID', f'segment_{i}')
            segment_name = attributes.get('Street', attributes.get('StreetName', f'Segment {i}'))
            
            documents[str(segment_id)] = {
                'doc_id': doc_id,
                'segment_name': segment_name,
                'source_field': doc_field,
                'attributes': attributes
            }
    
    print(f"✅ Extracted {len(documents)} document IDs\n")
    return documents


def save_segment_data(segments: List[Dict], documents: Dict) -> None:
    """Save segment and document data to JSON for reference."""
    
    # Save all segments
    segments_file = OUTPUT_DIR / "segments.json"
    with open(segments_file, 'w') as f:
        json.dump(segments, f, indent=2)
    print(f"  Segments saved to: {segments_file}")
    
    # Save document mappings
    docs_file = OUTPUT_DIR / "document_mappings.json"
    with open(docs_file, 'w') as f:
        json.dump(documents, f, indent=2)
    print(f"  Document mappings saved to: {docs_file}")
    
    # Save document IDs for later use
    ids_file = Path("document_ids.txt")
    with open(ids_file, 'w') as f:
        f.write("# Auto-extracted document IDs from segments\n")
        f.write("# Generated by fetch_all_segments.py\n\n")
        for seg_id, doc_info in documents.items():
            f.write(f"# Segment {doc_info['segment_name']}\n")
            f.write(f"{doc_info['doc_id']}\n\n")
    print(f"  Document IDs saved to: {ids_file}\n")


def fetch_onbase_document(document_id: str, output_file: str) -> bool:
    """Fetch a document from OnBase."""
    
    url = f"{ONBASE_API_URL}/{document_id}/"
    
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:150.0) Gecko/20100101 Firefox/150.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Sec-Fetch-Storage-Access": "none",
        "Connection": "keep-alive",
        "Referer": "https://onbasepublic.glastonbury-ct.gov/PavClient/PublicRecordTrafficCount/index.html?OBKey__102_1=MAIN%20ST",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "iframe",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-origin",
        "Sec-Fetch-User": "?1",
        "Priority": "u=4",
        "TE": "trailers"
    }
    
    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=TIMEOUT,
            stream=True,
            verify=False,
            allow_redirects=True
        )
        response.raise_for_status()
        
        # Check if we got a PDF or error JSON
        content_type = response.headers.get('content-type', '').lower()
        
        if 'application/json' in content_type or response.text.strip().startswith('{'):
            return False
        
        # Save the document
        with open(output_file, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
        
        file_size = Path(output_file).stat().st_size
        return file_size > 1000  # Must be larger than 1KB
        
    except Exception as e:
        return False


def batch_download_documents(documents: Dict, skip_existing: bool = True) -> None:
    """Download all documents."""
    
    print("=" * 60)
    print(f"📥 Downloading {len(documents)} documents")
    print("=" * 60 + "\n")
    
    successful = 0
    failed = 0
    skipped = 0
    
    for i, (seg_id, doc_info) in enumerate(documents.items(), 1):
        doc_id = doc_info['doc_id']
        segment_name = doc_info['segment_name']
        output_file = OUTPUT_DIR / f"document_{i:04d}_{seg_id}.pdf"
        
        # Skip if already exists
        if skip_existing and output_file.exists():
            print(f"[{i}/{len(documents)}] ⏭️  {segment_name} (exists)")
            skipped += 1
            continue
        
        print(f"[{i}/{len(documents)}] 📄 {segment_name}...", end=" ", flush=True)
        
        if fetch_onbase_document(doc_id, str(output_file)):
            file_size = output_file.stat().st_size / 1024
            print(f"✅ ({file_size:.1f} KB)")
            successful += 1
        else:
            print(f"❌")
            failed += 1
            # Clean up incomplete file
            if output_file.exists():
                output_file.unlink()
        
        # Rate limiting
        time.sleep(0.5)
    
    print(f"\n" + "=" * 60)
    print(f"Results: {successful} downloaded, {failed} failed, {skipped} skipped")
    print("=" * 60 + "\n")


def main():
    """Main execution."""
    parser = argparse.ArgumentParser(
        description="Download all traffic data from Glastonbury CT map server"
    )
    parser.add_argument("--no-download", action="store_true", help="Only extract, don't download")
    parser.add_argument("--force", action="store_true", help="Re-download existing files")
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("Traffic Data - All Segments Downloader")
    print("=" * 60 + "\n")
    
    # Step 1: Fetch all segments
    segments = fetch_all_segments()
    if not segments:
        print("❌ No segments found. Exiting.\n")
        return 1
    
    # Step 2: Extract document IDs
    documents = extract_document_ids_from_segments(segments)
    if not documents:
        print("⚠️  No document IDs found in segment attributes.")
        print("Checking for alternate data sources...\n")
    
    # Step 3: Save data
    print("💾 Saving segment data...")
    save_segment_data(segments, documents)
    
    # Step 4: Download documents
    if not args.no_download and documents:
        batch_download_documents(documents, skip_existing=not args.force)
    
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"Segments found: {len(segments)}")
    print(f"Documents extracted: {len(documents)}")
    print(f"Output directory: {OUTPUT_DIR.absolute()}")
    print("\nFiles created:")
    print(f"  • segments.json - All segment features")
    print(f"  • document_mappings.json - Segment to document mapping")
    print(f"  • document_ids.txt - List of document IDs")
    print(f"  • document_*.pdf - Downloaded PDFs")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
